# samples: Path to the CSV file containing the dataset
samples: "resources/data/Tab_suivi_mvad.csv"

# bdd_format: Format of the dataset (Long or Wide)
bdd_format: "Wide"

# var_id: Name of the identifier variable
var_id: "id"

# var_rep: Name(s) of the response variables (comma-separated list)
var_rep: "jul_93, aug_93, sep_93, oct_93, nov_93, dec_93, jan_94, feb_94, mar_94, apr_94, may_94, jun_94, jul_94, aug_94, sep_94, oct_94, nov_94, dec_94, jan_95, feb_95, mar_95, apr_95, may_95, jun_95, jul_95, aug_95, sep_95, oct_95, nov_95, dec_95, jan_96, feb_96, mar_96, apr_96, may_96, jun_96, jul_96, aug_96, sep_96, oct_96, nov_96, dec_96, jan_97, feb_97, mar_97, apr_97, may_97, jun_97, jul_97, aug_97, sep_97, oct_97, nov_97, dec_97, jan_98, feb_98, mar_98, apr_98, may_98, jun_98, jul_98, aug_98, sep_98, oct_98, nov_98, dec_98, jan_99, feb_99, mar_99, apr_99, may_99, jun_99"

# labels: Vector of labels for the response variable's states, in alphabetical order
labels: "Employement, Further Educ, High Educ, Joblessness, School, Training"

# path_result: Path to the folder where results should be exported
path_result: "results/plots"

# choix_criteres: Criteria preferences
choix_criteres: 
  # sequencement: Importance of sequencing TRUE/FALSE
  sequencement: "TRUE"
  
  # timing: Importance of timing TRUE/FALSE
  timing: "FALSE"
  
  # duree_etats: Importance of the duration of distinct states TRUE/FALSE
  duree_etats: "TRUE"
  
  # sequencement_perturbation: Importance of sensitivity to small perturbations TRUE/FALSE
  sequencement_perturbation: "FALSE"
  
  # timing_etatsRares: Specific interest in rare states TRUE/FALSE
  timing_etatsRares: "FALSE"
  
# expert: Expert mode enabled (1: Yes, 0: No)
expert: 0

#### Fill in only for expert mode ####

# dissimilarite_expert: Dissimilarity metrics provided by the expert (e.g., "OM, OMspell, LCS")
dissimilarite_expert: ""

# fusion_dissimilarites: Merge user-defined dissimilarities with those derived from criteria (1: Yes, 0: No)
fusion_dissimilarites: 0

# min_cluster_size: Minimum expected size for each cluster (NULL or numeric value)
min_cluster_size: NULL

# Parameter bounds by dissimilarity

# Dissimilarity: OM
bounds_OM:
  seqsubm: "c(0L,4L)"  # Integer values between 0 and 4

# Dissimilarity: OMstran
bounds_OMstran:
  seqsubm: "c(0L,4L)"  # Integer values between 0 and 4 
  transindel: "c(0L,2L)"  # Integer values between 0 and 2
  otto: "c(0.0001, 1)"

# Dissimilarity: OMspell
bounds_OMspell:
  seqsubm: "c(0L,4L)"  # Integer values between 0 and 4
  expcost: "c(0,3)"

# Dissimilarity: SVRspell
bounds_SVRspell:
  a: "c(0,3)"
  b: "c(0,3)"
  tpow: "c(0, 3)"

