__use_yte__: true
datasets:
  seq:
    path: ?input.table
    separator: ;
views:
  seq:
    dataset: seq
    render-table:
      columns:
        Time_1:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        Time_2:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        Time_3:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        Time_4:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        Time_5:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        Time_6:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        Time_7:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        Time_8:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        Time_9:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        Time_10:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        Time_11:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        Time_12:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        Time_13:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        Time_14:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        Time_15:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        Time_16:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        Time_17:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        Time_18:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        Time_19:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        Time_20:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        Time_21:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        Time_22:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        Time_23:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        Time_24:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        Time_25:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        Time_26:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        Time_27:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        Time_28:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        Time_29:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        Time_30:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        Time_31:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        Time_32:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        Time_33:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        Time_34:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        Time_35:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        Time_36:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        Time_37:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        Time_38:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        Time_39:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        Time_40:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        Time_41:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        Time_42:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        Time_43:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        Time_44:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        Time_45:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        Time_46:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        Time_47:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        Time_48:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        Time_49:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        Time_50:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        Time_51:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        Time_52:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        Time_53:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        Time_54:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        Time_55:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        Time_56:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        Time_57:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        Time_58:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        Time_59:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        Time_60:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        Time_61:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        Time_62:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        Time_63:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        Time_64:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        Time_65:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        Time_66:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        Time_67:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        Time_68:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        Time_69:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        Time_70:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        Time_71:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        Time_72:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        cluster:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
